### ISSUE TITLE
Update behavior of differential-expression model define and start

### ISSUE THREAD

**Issue by malachig** [genome/gms#114]
We are having a few minor issues with differential expression models in the sGMS.  These are not specific to the sGMS but potentially affect the flow of our tutorials.  Each seems pretty minor:

1.) It seems that you can not create a differential-expression model unless rna-seq _builds_ exist.  This seems inconsistent with the rest of the system.  You should be able to create a model even if the underlying input models do not have builds yet.  Similar to somatic-variation, clin-seq, etc.

2.) In the sGMS,  we get around (1) by priming a differential expression model in the database as part of a metadata dump. However, if you start this model before one or both of the rna-seq models has a successful build you get some weird errors.  In other words, it tries to run and chokes.  Elsewhere in the system, the model would be considered unstartable if there was no successful build of an input model.  You would be warned right away and the user would have a hint to check their input models.

3.) When defining differential-expression models, you are required to specify model ids.  This is one of relatively few places in the system where you must use an ID.  I see why this a string of entities is needed here to allow for different combinations of replicates and condition groups.  As described in the docs:  Each group (A, B, C & D) is separated by white space. ex: "1,2 3,4 5,6 7,8".  Make sense.  But could be have an option to specify these as model names instead?

That way you can document a workflow of commands in advance without asking the user to run a command, see what random ID was created and then enter that...

**Comment by ghost** [comment]
(1) and (2) were solved by moving the check for a successful build of the rna-seq models into the _resolve_workflow_for_build() method of Genome::Model::DifferentialExpression.

I have one solution for (3).  After talking it over with some of my colleagues, I'm going to make some changes since they would like to see a different solution.

**Comment by malachig** [comment]
@mkiwala-g is it your opinion that this issue is now resolved?

**Comment by ghost** [comment]
Parts 1 and 2 above are resolved.  A solution to part 3 was never pushed, but the sample import script and clinseq update-analysis already are designed to define differential expression models by using IDs instead of model names.

Since clinseq-update analysis is the preferred approach to guiding users to define differential expression models, solving part 3 does not seem important.
