### ISSUE TITLE
Update APT repo for Ubuntu precise to include new software that has been debian packaged

### ISSUE THREAD

**Issue by malachig** [genome/gms#119]
Some GMS dependencies have been Debian packaged since the last merge (and or since the installer was created).  We should switch from installing these in ad hoc way to using the debian packages.

In order to do this we need to identify dependencies added to genome-snapshot-deps lucid, and add them to genome-snapshot-deps for precise.  Top priorities for this are:
- libset-intervaltree-perl (>= 0.07-1)
- bam-readcount0.5 (>= 0.5.1)
- libgetopt-complete-perl (>= 0.20-1)
- libmodule-runtime-perl (>= 0.014-1)
- libdbd-pg-perl (>=2.19.3-2)

Once this is done, the Makefile should be updated to drop ad hoc installation of each dependency.  For example, several libraries are currently installed by `cpanm` but we can now get these as debs.

**Comment by malachig** [comment]
With the perl packages above we are running into a dependency problem with ubuntu precise, that is that each of these packages relies on perlapi-5.10.1 but we are getting this error:

`Depends: perlapi-5.10.1 but it is not installable`

**Comment by malachig** [comment]
@kindjal has rebuilt the perl lib debian packages above for Ubuntu precise.  While testing, they are in a development apt repo here:  http://repo.gsc.wustl.edu/dev/ubuntu/pool/precise-genome-development/main/

This can be added as an apt.source as follows (/etc/apt/sources.list.d/genome.list):
deb http://repo.gsc.wustl.edu/dev/ubuntu precise-genome-development main

Once we confirm that these install in Ubuntu precise, he will move them over to the non dev apt repo and we can build a new APT tarball...

**Comment by malachig** [comment]
I was able to successfully install `libset-intervaltree-perl` and `libmodule-runtime-perl`

There were problems with the other two:

`libdbd-pg-perl` seems to still be missing...

and

`libgetopt-complete-perl` did _not_ work:

```
sudo apt-get install libgetopt-complete-perl 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgetopt-complete-perl : Depends: perl (>= v5.8.7) but 5.14.2-6ubuntu2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mcallaway** [comment]
I've added these to the dev/ubuntu repo:

libdbd-pg-perl_3.0.0_amd64.deb
libgetopt-complete-perl_0.26_all.deb

It turns out the Getopt::Complete source Build.PL has "v5.8.7" for the perl dependency, and the "v" is a packaging violation. I manually fixed it at build time. Now the dependency in the .deb looks like:

 Depends: perl (>= 5.8.7)

Which should be satisfied. Observe:

```
> dpkg --compare-versions "5.14.2-6ubuntu2" ">=" "v5.8.7" ; echo $?;
dpkg: warning: version 'v5.8.7' has bad syntax: version number does not start with digit
1

-> dpkg --compare-versions "5.14.2-6ubuntu2" ">=" "5.8.7" ; echo $?;
0
```

The packages are now present in the repo. Please retry your test.

**Comment by malachig** [comment]
My test environment is an sGMS install with the current APT configuration _plus_ `deb http://repo.gsc.wustl.edu/dev/ubuntu precise-genome-development main`.   All four of the missing perl libraries can now be installed for Ubuntu precise from Deb packages.

**Comment by malachig** [comment]
Another needed package we are missing for Ubuntu precise has been identified: `lucid/genome-snapshot-deps-apps-external.depends:circos0.64` needs to be added to `precise/genome-snapshot-deps-apps-external.depends` in genome-snapshot-deps and then the APT repo needs to be rebuilt.

**Comment by malachig** [comment]
With the latest APT package `ubuntu-12.04-2014.03.07` I now get this error:

```
The following packages have unmet dependencies:
 libdbd-pg-perl : Depends: perl-dbi (>= 1.614) but it is not installable
                  Depends: perl (>= 5.008001) but 5.14.2-6ubuntu2.4 is to be installed
                  Depends: perl-version but it is not installable
E: Unable to correct problems, you have held broken packages.
```

The other 4 mentioned above install successfully from the package.  If I switch back to using the 'dev' repo it does not work.  Weird, it seemed that was working yesterday...

**Comment by gatoravi** [comment]
In the current APT dump (2014.03.10) this is the status of these packages 

libset-intervaltree-perl (>= 0.07-1) - installs and works.
bam-readcount0.5 (>= 0.5.1) - installs and works.
libgetopt-complete-perl (>= 0.20-1) - installs and works

libmodule-runtime-perl (>= 0.014-1) - installs but does not work, we get

``` bash
vagrant@precise64 /opt/gms/MYNAC53/sw/genome/lib/perl (gms-pub-testmerge3)> perl -e 'use Module::Runtime'
Can't locate Module/Runtime.pm in @INC (@INC contains: /opt/gms/MYNAC53/sw/ur/lib /opt/gms/MYNAC53/sw/workflow/lib /opt/gms/MYNAC53/sw/genome/lib/perl/x86_64-linux-gnu-thread-multi /opt/gms/MYNAC53/sw/genome/lib/perl /opt/gms/MYNAC53/sw/genome/lib/perl-added /usr/lib/perl5/x86_64-linux-gnu-thread-multi/ /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

libdbd-pg-perl (>=2.19.3-2) - Installs but does not work, we get this error

``` bash
vagrant@precise64 /opt/gms/MYNAC53/sw/genome/lib/perl (gms-pub-testmerge3)> perl -e 'use DBD::Pg'
Unable to get DBI state function. DBI not loaded. at /usr/lib/perl/5.14/DynaLoader.pm line 207.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

**Comment by mcallaway** [comment]
libmodule-runtime-perl was repackaged and deployed to repos. Working on DBD::Pg now.

**Comment by mcallaway** [comment]
libdbd-pg-perl has been repackaged and deployed to repos. Give it a shot.

**Comment by malachig** [comment]
In a fresh install I now get this error:

```
perl -e 'use DBD::Pg'
Can't load '/usr/lib/perl/5.14/auto/DBD/Pg/Pg.so' for module DBD::Pg: libpq.so.5: cannot open shared object file: No such file or directory at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at -e line 1
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

**Comment by gatoravi** [comment]
when I do a `sudo apt-cache showpkg libdbd-pg-perl` on my install, 

``` bash
Dependencies: 
3.0.0 - perl (0 (null)) libdbi-perl (0 (null)) 
2.19.3-2 - perl (2 5.10.1-8ubuntu2.1) perlapi-5.10.1 (0 (null)) libc6 (2 2.4) libpq5 (2 8.4~0cvs20090328) libdbi-perl (2 1.52) 
2.19.0-1 - perl (2 5.14.2-6ubuntu1) perl-dbdabi-94 (0 (null)) perlapi-5.14.2 (0 (null)) libc6 (2 2.14) libpq5 (2 8.4~) 
```

maybe missing dependencies for this version ?

**Comment by malachig** [comment]
Test all four problematic perl libraries being installed from Deb packages:

deb http://repo.gsc.wustl.edu/ubuntu precise-genome-development main 
deb http://repo.gsc.wustl.edu/ubuntu lucid-genome-development main

sudo apt-get install bam-readcount0.5
sudo apt-get install libdbd-pg-perl
sudo apt-get install libset-intervaltree-perl
sudo apt-get install libgetopt-complete-perl
sudo apt-get install libmodule-runtime-perl

bam-readcount0.5
perl -e 'use DBD::Pg'
perl -e 'use Set::IntervalTree'
perl -e 'use Getopt::Complete'
perl -e 'use Module::Runtime'

In a completely vanilla Ubuntu install (precise64 from vagrant but without GMS installed at all) this is all working now.  We should once again rebuild the APT tarball and test that in the GMS install Makefile

**Comment by gatoravi** [comment]
On a fresh apt-repo dump all these packages seem to install correctly, but now.... priming fails due to incorrect version of DBD::Pg !!

sudo bash -l -c 'source /etc/genome.conf; /usr/bin/perl setup/prime-disk-allocations.pl'
setting GENOME_\* variables...
updating PATH, PERL5LIB, and CLASSPATH for the GMS
configuring tab-completion...
ERROR: ***\* INCORRECT POSTGRES DRIVER VERSION ****
You are using a Perl version that includes an incorrect DBD::Pg driver.
You are running 3.0.0 and need to be running 2.19.3.
Your sync has been aborted to protect data integrity in the Postgres database.
Please be sure you are using 'genome-perl' and not /gsc/bin/perl.

This event has been logged with apipe; if you are unsure of why you received this message
open an apipe-support ticket with the date/time of occurrence and we will assist you.
Couldn't open /gsc/var/log/genome/postgres//2014/3-11.log for appending: No such file or directory
Error while autoloading with 'use Genome::InstrumentData': Can't resolve data source from value 'Genome::DataSource::GMSchema' in class definition for Genome::InstrumentData
Error while autoloading with 'use Genome::DataSource::GMSchema': ***\* INCORRECT POSTGRES DRIVER VERSION ****
You are using a Perl version that includes an incorrect DBD::Pg driver.
You are running 3.0.0 and need to be running 2.19.3.
Your sync has been aborted to protect data integrity in the Postgres database.
Please be sure you are using 'genome-perl' and not /gsc/bin/perl.

This event has been logged with apipe; if you are unsure of why you received this message
open an apipe-support ticket with the date/time of occurrence and we will assist you.
BEGIN failed--compilation aborted at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome/DataSource/CommonRDBMS.pm line 196.
Compilation failed in require at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome/DataSource/GMSchema.pm line 7.
BEGIN failed--compilation aborted at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome/DataSource/GMSchema.pm line 7.
Compilation failed in require at (eval 536) line 2.
BEGIN failed--compilation aborted at (eval 536) line 2.
 at /opt/gms/GS5IC32/sw/ur/lib/UR/ModuleLoader.pm line 83
 at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome/InstrumentData.pm line 8
Compilation failed in require at (eval 529) line 2.
BEGIN failed--compilation aborted at (eval 529) line 2.
 at /opt/gms/GS5IC32/sw/ur/lib/UR/ModuleLoader.pm line 83
Compilation failed in require at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome/Patch.pm line 9.
Compilation failed in require at /opt/gms/GS5IC32/sw/genome/lib/perl/Genome.pm line 87.
Compilation failed in require at setup/prime-disk-allocations.pl line 4.
BEGIN failed--compilation aborted at setup/prime-disk-allocations.pl line 4.
make: **\* [done-host/db-schema] Error 2
make[1]: **\* [setup] Error 2
rm done-repo/download-java-2013-08-27.tgz
make[1]: Leaving directory `/vagrant'
make: **\* [all] Error 2

**Comment by gatoravi** [comment]
Just FYI, we cannot install the lucid version of libdbd-pg-perl2.19.3 as this is packaged for an older version of perl that comes w lucid. Looks like we might need libdbd2.19.3 packaged for precise.

vagrant@precise64 /vagrant (ubuntu-12.04)> sudo apt-get install libdbd-pg-perl=2.19.3-2
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdbd-pg-perl : Depends: perlapi-5.10.1 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by malachig** [comment]
This message come from here:

Genome/DataSource/CommonRDBMS.pm

``` perl
sub _check_pg_version {
    my $class = shift;

    my $required_pg_version = '2.19.3';
    require DBD::Pg;
    my $pg_version = $DBD::Pg::VERSION;
    if (($pg_version ne $required_pg_version) && !defined $ENV{'LIMS_PERL'}) {
        my $error_message = "**** INCORRECT POSTGRES DRIVER VERSION ****\n" .
            "You are using a Perl version that includes an incorrect DBD::Pg driver.\n" .
            "You are running $pg_version and need to be running $required_pg_version.\n" .
            "Your sync has been aborted to protect data integrity in the Postgres database.\n" .
            "Please be sure you are using 'genome-perl' and not /gsc/bin/perl.\n\n\n" .
            "This event has been logged with apipe; if you are unsure of why you received this message\n" .
            "open an apipe-support ticket with the date/time of occurrence and we will assist you.\n";
        UR::Object->error_message($error_message);
        log_error($error_message);
        die $error_message;
    }
}
```

I guess we could try setting this to the newer version...  Hard to say what the possible implications of that might be.  Obviously would be safer to just be on the same version of DBB::Pg.  It can install and run on precise via CPAN, so this is still a Debian packaging issue presumably...

**Comment by gatoravi** [comment]
changing `my $required_pg_version = '3.0.0';` helps the installation and the priming of the database succeed and the model listers work fine. More extensive testing is needed to ensure that this version of the driver does not cause any unforeseen issues, hard to tell right now. An alternate route that we might take is to just package version 2.19.3 for precise.

**Comment by gatoravi** [comment]
From @amb43790 :
I can't say whether there would be problems or not looking at the changelogs and testing.The check was added in dec 2012 to avoid a problem when we were syncing to both Oracle and Postgres.  I don't recall the details of the problem, but it had something to do with Lims's  perl (5.8) DBD::Pg being too old.

**Comment by gatoravi** [comment]
This version-check has been relaxed by @amb43790 in master here https://github.com/genome/gms-core/commit/e42c96331b69a363f0619da873628ba49dbdc67a and in gms-pub here https://github.com/genome/gms-core/commit/fa261aa68928bfe0bbeafcee187c24a5461f9eaf
At this point in time it's hard to see problems with this, we will have to test this out to find them.

**Comment by malachig** [comment]
Update list of tests to make sure all new packages are working after a clean sGMS install using only Debian packages for these:

sudo apt-cache policy bam-readcount0.5
sudo apt-cache policy libdbd-pg-perl
sudo apt-cache policy libset-intervaltree-perl
sudo apt-cache policy libgetopt-complete-perl
sudo apt-cache policy libmodule-runtime-perl
sudo apt-cache policy libsort-strverscmp-perl
sudo apt-cache policy circos0.64

bam-readcount0.5
perl -e 'use DBD::Pg'
perl -e 'use Set::IntervalTree'
perl -e 'use Getopt::Complete'
perl -e 'use Module::Runtime'
perl -e 'use Genome::Model::Tools::Bed::ChromSort'
circos0.64

**Comment by malachig** [comment]
Use of `cpanm` was eliminated entirely from the GMS installation in this commit: https://github.com/genome/gms/commit/2c4cc7d6677f423dd0a2b1017839b8f9dc4f9b6e

**Comment by malachig** [comment]
`libsort-strverscmp-perl` is still missing as a dependency.  It is available to be installed and works with `sudo apt-get install libsort-strverscmp-perl` but it just isn't happening automatically.  @gatoravi is working on a minor tweak of the apt repo.

**Comment by gatoravi** [comment]
This seems to be fixed in the new dump now. (2014.03.12)

**Comment by malachig** [comment]
Confirmed.  Also worked for me.

**Comment by malachig** [comment]
All of these dependencies are now installed as Debian packages.  Where necessary they have been rebuilt for Ubuntu Precise.  Closing this issue now.
