### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#17]
I feel like I've seen this happen a half dozen times now but I can't understand the problem or recall how it was fixed. Trying to do a fresh install but getting tripped up at an early stage by permissions. Is this an issue that only comes up because I'm symlinking /opt/gms to /data/opt-gms/?
# set permissions on the root directory above the GMS home so that additional systems can attach

sudo chown genome:genome /opt/gms /opt/gms/.*
sudo chown genome:genome /opt/gms /opt/gms/.*
sudo chmod g+rwxs /opt/gms /opt/gms/.*
### FIX: note that the above uses "/opt/gms/.*", and as such will not change permissions on /opt/gms/NOPJ410, since NOPJ410 does not start with "."
# make the home for this GMS

[ -d "/opt/gms/NOPJ410" ] || sudo mkdir -p /opt/gms/NOPJ410
echo GMS_HOME is /opt/gms/NOPJ410
GMS_HOME is /opt/gms/NOPJ410
# install a directory skeleton

cp -a setup/gms-home-skel/\* /opt/gms/NOPJ410
cp: cannot create directory `/opt/gms/NOPJ410/db': Permission denied
cp: cannot create directory`/opt/gms/NOPJ410/export': Permission denied
cp: cannot create directory `/opt/gms/NOPJ410/fs': Permission denied
cp: cannot create directory`/opt/gms/NOPJ410/known-systems': Permission denied
cp: cannot create directory `/opt/gms/NOPJ410/sw': Permission denied
cp: cannot create directory`/opt/gms/NOPJ410/tmp': Permission denied
cp: cannot create directory `/opt/gms/NOPJ410/var': Permission denied
make[1]: *** [done-host/gms-home] Error 1
make[1]: Leaving directory`/home/ogriffit/gms'
make: **\* [all] Error 2

**Comment by mcallaway** [comment]
Note that operations within the VM via Vagrant happen as the vagrant user.
Everything root must happen with sudo. This is pretty fundamental and since
you all have been working with this for a while I wonder what must've
changed for this to stop working. Check the make file to see if sudo is
missing in ops within the VM.

I'll try to look at this myself later today.

On Oct 8, 2013, at 12:09 AM, obigriffith notifications@github.com wrote:

I feel like I've seen this happen a half dozen times now but I can't
understand the problem or recall how it was fixed. Trying to do a fresh
install but getting tripped up at an early stage by permissions. Is this an
issue that only comes up because I'm symlinking /opt/gms to /data/opt-gms/?
set permissions on the root directory above the GMS home so that additional
systems can attach

sudo chown genome:genome /opt/gms /opt/gms/.*
sudo chown genome:genome /opt/gms /opt/gms/.*
sudo chmod g+rwxs /opt/gms /opt/gms/.*
make the home for this GMS

[ -d "/opt/gms/NOPJ410" ] || sudo mkdir -p /opt/gms/NOPJ410
echo GMS_HOME is /opt/gms/NOPJ410
GMS_HOME is /opt/gms/NOPJ410
install a directory skeleton

cp -a setup/gms-home-skel/\* /opt/gms/NOPJ410
cp: cannot create directory /opt/gms/NOPJ410/db': Permission denied
cp: cannot create directory/opt/gms/NOPJ410/export': Permission denied
cp: cannot create directory /opt/gms/NOPJ410/fs': Permission denied
cp: cannot create directory/opt/gms/NOPJ410/known-systems': Permission
denied
cp: cannot create directory /opt/gms/NOPJ410/sw': Permission denied
cp: cannot create directory/opt/gms/NOPJ410/tmp': Permission denied
cp: cannot create directory /opt/gms/NOPJ410/var': Permission denied
make[1]: **\* [done-host/gms-home] Error 1
make[1]: Leaving directory/home/ogriffit/gms'
make: **\* [all] Error 2

—
Reply to this email directly or view it on
GitHubhttps://github.com/genome/gms/issues/17
.

**Comment by malachig** [comment]
Hi Matt,

Sorry should have explained this better in advance.  So there are two tests going on here at once.  Corresponding to the two main arms of the GMS makefile.  
1. Malachi is testing on a Mac Pro by installing the GMS into a vagrant VM ubuntu 12.04.
2. Obi is testing on a Dell server by installing GMS into a fresh ubuntu 12.04 installation.  No VM is involved in that test.  

The makefile does things that detect which environment the user is in.  If within a VM, things are done as the 'vagrant' user.  On a fresh ubuntu install, this is not the case...

**Comment by sakoht** [comment]
This was the issue of logging out and back in, right?

The directory is owned by the genome group, and your user was added to that group, but until you log out and back in it doesn't take effect.

Does that handle it?

(We have the last thing in the make file tell the user to log out, in a hopefully emphatic way.)

**Comment by obigriffith** [comment]
Matt. Sorry. We have so many different tests going on this gets 
confusing. The problem I am having is nothing to do with VM or Vagrant 
since my test is on a standalone ubuntu box at home. Vagrant/VM not 
being used.

**Comment by sakoht** [comment]
The problem is that the directories do not have write permission, even though the owner is correct, and it is "group sticky" (sub-directories will have the group genome regardless of the user's default group.

drwxr-sr-x 2 root genome 4096 Oct  7 23:57 NOPJ410
drwxr-xr-x 9 root root   4096 Oct  7 23:51 X0KZ365

The fast fix is "chmod g+rwxs+ /opt/gms/*".

It looks like line 364 in the Makefile should have done this, but because it was re-done as part of manually rearranging the directories, this part was missed.

I'm correcting the permissions now, and putting a note in the issue above.
