### ISSUE TITLE
Makefile is attempting to get an old version of APP_DUMP

### ISSUE THREAD

**Issue by malachig** [genome/gms#18]
Encountered this error while running make on a GMS VM installation:

cd setup/archive-files; wget -v -c http://genome.wustl.edu/pub/software/gms/testdata/GMS1/setup/archive-files/`basename done-repo/download-apt-mirror-min-ubuntu-12.04-20130906.150956.tgz | sed s/download-//` 
--2013-10-21 03:45:23--  http://genome.wustl.edu/pub/software/gms/testdata/GMS1/setup/archive-files/apt-mirror-min-ubuntu-12.04-20130906.150956.tgz
Resolving genome.wustl.edu (genome.wustl.edu)... 10.0.97.9
Connecting to genome.wustl.edu (genome.wustl.edu)|10.0.97.9|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2013-10-21 03:45:23 ERROR 404: Not Found.

Indeed that file seems to be missing and a newer one seems to be in place...

**Comment by malachig** [comment]
Updated the Makefile from this:
APT_DUMP_VERSION=20130906.150956

To this:
APT_DUMP_VERSION=2013.10.19

**Comment by sakoht** [comment]
Ah good it finally staged.  It hadn't when I hit the road.

Did the make process complete afterward?

Wifi here isn't working well.  Tried to log in but keep losing connection.  I did push the change so this will rebuild the mirror:

  cd setup/stage
  make

Though an edit like the one you made needs to be done each time to start using the new file, once it goes up.

**Comment by malachig** [comment]
It did work all the way through as far as I can tell!  Do you still need me to rebuild the mirror again?

**Comment by sakoht** [comment]
Not if it worked!  That one you are liking at was made by me in a cafe yesterday.

We could look in the setup/etc/sources.list.d+\* files and mirror those too to shirks against outside failures.

Next is to be sure the exome stuff runs after a new FTP sync of the data, since I added those files.

Then run "genome db cosmic install v65.1" or whatever the ClinSeq build needs.  You could make that part if update-analysis actually, and avoid waiting for anything not automatic.

We may need a similar installer for the other two DBs.  I'd need to get on working wifi to see if all three are there or just one.  Probably virtually cut-and-paste.

Call me if you want to talk through anything?  Driving 11.5 more hours today...

**Comment by malachig** [comment]
This issue appears to be fixed for now.  It will likely recur periodically but right now the install appears to be working smoothly.  Closing for now.
