### ISSUE TITLE
Re-priming the system

### ISSUE THREAD

**Issue by shu2010** [genome/gms#194]
Is there a way to re-prime the system without having the destroy the VM and re-install?
Thanks
Shu

**Comment by gatoravi** [comment]
I don't think this is possible, I'm cc'ing @sakoht and @malachig who might be able to advise better. `make db-drop` and `make db-rebuild` will get rid of the database tables and rebuild them but I don't think that's the step you are talking about here. Are you referring to running this script?
`./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=tarball`

**Comment by sakoht** [comment]
Shu when you say you want to re-prime, what would you like to change/fix?

The primary goal of the prime-system script it to fill the starting database with a set of example models.  Do you want to delete and re-add those?  Or something else?

**Comment by shu2010** [comment]
@gatoravi , yes I am referring to the script: ./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=tarball..

@sakoht, I would like to change the system configurations like memory, storage, cpus etc.. 
Also, I would like to add my own samples to the system and **utilise the parameters** from the existing processing-profiles, models and builds.. If I start with data=none, these parameters are reset and I would have to populate the parameters from scratch which I want to avoid during this run.

**Comment by sakoht** [comment]
> On Nov 24, 2015, at 2:39 PM, shu2010 notifications@github.com wrote:
> 
> @gatoravi , yes I am referring to the script: ./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=tarball..
> 
> @sakoht, I would like to change the system configurations like memory, storage, cpus etc.. 

If you can change those parameters on the current VM.

**Comment by sakoht** [comment]
Sent from my iPhone

> On Nov 24, 2015, at 2:39 PM, shu2010 notifications@github.com wrote:
> 
> @gatoravi , yes I am referring to the script: ./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=tarball..
> 
> @sakoht, I would like to change the system configurations like memory, storage, cpus etc.. 

Whether you can do that on the same VM or need a new VM depends on the VM system you are using.  If you _must_ make a new VM with those parameters, you can probably detach the drives, and re-attach them to the new VM after bringing it up.

You will probably repeat much of the install process, though, since you need things like package installation, server config, etc.

> Also, I would like to add my own samples to the system and utilise the parameters from the existing processing-profiles, models and builds.. If I start with data=none, these parameters are reset and I would have to populate the parameters from scratch which I want to avoid during this run.

Yeah the whole idea of having the examples is to make it easy to process your own in the exact same way.  Let the system be primed with default data.  Then import your own instrument data, and make new models with the existing processing profiles.
