### ISSUE TITLE
permissions issue while creating directory in blade.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#36]
Permissions issue, 

ssmith@blade16-4-16 ~> genome model build start tst1-tumor-snparray 
'models' may require verification...
Resolving parameter 'models' from command argument 'tst1-tumor-snparray'... found 1
Trying to start # 1: tst1-tumor-snparray (2891230328)...
ERROR: Failed to create directory (/opt/gms/DY46678/fs/DY46678/info/model_data/2891230328/buildd49fe7a2489c11e386e07750675ac08a) with return value = '', and error:
Can't mkdir('/opt/gms/DY46678/fs/DY46678/info/model_data'): Permission denied at /opt/gms/DY46678/sw/genome/lib/perl/Genome/Sys.pm line 838

Not sure why this is happening.

**Comment by malachig** [comment]
Is this perhaps related to: #24 ?

**Comment by malachig** [comment]
I believe this issue is resolved by further testing of the installation.  Some additional commands are now executed as 'sudo'.  Additional commands are used to reset ownership and permissions during the make process.  These kind of problems can occur if the user forgets to log out and log back in at the end of the installation.  I have made the related warning at the end of the installation more prominent.  (5b291735b6b4640abd2be5ea72ed24561fe9cbdc)
