### ISSUE TITLE
schema does not exist.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#37]
While starting a build it complains about not finding a schema called "timeline"

ssmith@blade16-4-16 ~> genome model build start tst1-tumor-snparray 

DBD::Pg::st execute failed: ERROR:  schema "timeline" does not exist
LINE 3: from timeline.allocation
             ^ at /opt/gms/DY46678/sw/ur/lib/UR/DBI.pm line 888.
ERROR: Failed to execute SQL 
select timeline.allocation.absolute_path, timeline.allocation.created_at, timeline.allocation.created_by, timeline.allocation.id, timeline.allocation.kilobytes_requested, timeline.allocation.name, timeline.allocation.object_class_name, timeline.allocation.object_id, timeline.allocation.reason, timeline.allocation.status, timeline.allocation.updated_at
from timeline.allocation
where timeline.allocation.object_class_name = ?
and timeline.allocation.object_id = ?
order by timeline.allocation.id

**Comment by jeldred** [comment]
this is probably related to recent additions that got merged back from
master for tracking allocation changes

> While starting a build it complains about not finding a schema called
> "timeline"
> 
> ssmith@blade16-4-16 ~> genome model build start tst1-tumor-snparray
> 
> DBD::Pg::st execute failed: ERROR:  schema "timeline" does not exist
> LINE 3: from timeline.allocation
>              ^ at /opt/gms/DY46678/sw/ur/lib/UR/DBI.pm line 888.
> ERROR: Failed to execute SQL
> select timeline.allocation.absolute_path, timeline.allocation.created_at,
> timeline.allocation.created_by, timeline.allocation.id,
> timeline.allocation.kilobytes_requested, timeline.allocation.name,
> timeline.allocation.object_class_name, timeline.allocation.object_id,
> timeline.allocation.reason, timeline.allocation.status,
> timeline.allocation.updated_at
> from timeline.allocation
> where timeline.allocation.object_class_name = ?
> and timeline.allocation.object_id = ?
> order by timeline.allocation.id
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/genome/gms/issues/37

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by malachig** [comment]
#Details on how to interrogate the genome database (including credentials) with the TGI can be found here:
genome/lib/perl/Genome/DataSource/GMSchema.pm 

#Within the standalone GMS the schema is created according to the definition here in the GMS repo:
gms/setup/schema.psql

#From within the standalone GMS you can query the PostGres genome schema as follows:
% sudo -u postgres pg_dump -s genome

#From within the TGI you can query the PostGres genome schema as follows:
% pg_dump -s genome --username gms-user --host gms-postgres

#In order to get that to work you need your version of pg_dump to match that the server is running.  I'm not sure where we store those...
#Maybe the safest thing is to just log into the postgres server on the TGI side and run the command there:
% ssh gms-postgres
% pg_dump -s genome --username gms-user --host gms-postgres

#Unfortunately that gives me this error:
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema workflow
pg_dump: [archiver (db)] query was: LOCK TABLE workflow.instance_execution IN ACCESS SHARE MODE

#If I limit to a particular schema of interest, say 'timeline' that started this whole business it works though:
% pg_dump -s genome --username gms-user --host gms-postgres -n timeline

#Now we have new schema creation, table creation, table alteration, etc. commands that need to be added to gms/setup/schema.psql.  It is not as simple as pasting them in though because there are some commands related to user permissions that need to be configured slightly for standalone GMS.  Some commands can be safely dropped because they are redundant with commands already in gms/setup/schema.psql.

#Once those commands are added you can test them by doing 'make db-rebuild' and then rerun 'genome model import metadata' with your data dump file as described in the tutorial.

**Comment by malachig** [comment]
It should be noted that the above hoop jumping of patching the schema when we merge code changes from gms-core master into pub could be avoided if we simply grabbed the entire schema definition in use within the TGI at the time the code is merged.  There is one problem with this though:
- To some degree we are still using both 'workflow' AND the newer 'flow/ptero' for workflow management.  At least this appears to be true within the TGI.  In the standalone GMS we are just using 'workflow'.
- 'workflow' within the TGI was left using an Oracle database.  We can't make Oracle portable so in the standalone GMS we moved the related tables into postgres.  Within TGI this has not happened. 
- So either way we have to manually patch around this issue.

Possible solutions.  (a) Develop a practice of dumping the entire schema from TGI and have an automated process for adding in what we needed for the old workflow system.  (b) keep doing what we are doing.  (c) stop using workflow and use flow/ptero exclusively.  Even in this case there may be modifications to the schema that are required to handle permissions issues specific to the standalone environment.

**Comment by ernfrid** [comment]
I believe Ptero is still using the Oracle schema for storing history and status so (c) may not help you either.

**Comment by malachig** [comment]
Ah, ok.  That's good to know.  Perhaps (a) is the lesser of evils then.  For now we will probably try (b) though.

**Comment by malachig** [comment]
Avi wound up taking the approach described in (a).  He then diffed the new schema against the old schema used in the standalone GMS and added in those elements needed to keep 'workflow' working.  Everything seems to be working now up to the point we were previously at.

Avi, can you comment here on what exactly needed to be added into the Postgres schema?

**Comment by gatoravi** [comment]
The classes in the gms seemed to be looking for tables under a schema called 'timeline' which did not exist under the old schema.psql dump file. I copied over that schema and all the tables from a latest dump that I did at TGI  it to the psql file. I also had to manually update the columns of two  tables (disk.allocation and subject.user) to reflect the latest schema since these columns were being accessed by the perl modules.

**Comment by malachig** [comment]
This issue has been resolved.  We have now performed the standalone gms installation on multiple systems without problems.  We have also obtained successful microarray and reference-alignment (exome) builds that appear to contain valid results.  A tumor rna-seq build launches successfully and we are waiting to see if it can run through to completion.  The first several steps in the workflow do complete successfully...

Overall we are now well past the point we were before the gms-core master to gms-core pub merge. Several schema changes occurred at that time but we seem to have resolved all of them.  At least to the point we were at before the merge...  Testing continues but I'm closing this specific issue.
