### ISSUE TITLE
Could not find a group with name info_genome_models

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#38]
When the stated errors are suppressed and when I try to start a build, I get this error.
![screen shot 2013-11-11 at 1 44 32 pm](https://f.cloud.github.com/assets/764948/1515866/e38e5306-4b09-11e3-9e69-49fdda2001cf.png)

**Comment by malachig** [comment]
What happens when you do this?

% genome disk group list

When I do that I do see a disk group with name 'info_genome_models'.

**Comment by gatoravi** [comment]
I don't see any disk groups listed, I'm guessing this might have to do with the .psql dump file(the entire dump) that I imported.

**Comment by malachig** [comment]
It sounds like this issue was probably just due to an installation that was in a half-baked state.  See if it recurs after your next clean install and then close or update this issue accordingly.

**Comment by malachig** [comment]
This issue did not recur.  When doing tests on a standard Ubuntu 12.04 box it is important to note that in order to retest the installation from scratch the safest approach is to re-image the machine back to a completely fresh state (i.e. as if installation of the OS had just completed).  If you are using extra volumes for data storage, for example, mounting /opt/gms to a volume other than that used for the system, you will also want to reformat that volume (or at least remove all files).
