### ISSUE TITLE
"genome db install" doesn't work. ERROR: Could not find the gaps file located at /gaps.csv

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#50]
When a somatic variation build is started the   'cnv plot-cnv v1' step crashes with 

ERROR: Could not find the gaps file located at /gaps.csv

the location of gaps.csv is determined in /opt/gms/GD0T679/sw/genome/lib/perl/Genome/Model/Tools/CopyNumber/PlotSegmentsFromBamsWorkflow.pm  

by this line

`my $file = Genome::Sys->dbpath("tgi-misc-annotation","human-build$refseq_version-20130113") . "/$file_type.csv";`

I think this is because the "tgi-misc-annotation" database is not being installed correctly.

Does the git repository for that database hold the right data ?

TODO- Reference original db install issue here.

**Comment by malachig** [comment]
This issue is related to issue #13.  Until we figure out how to get these file based DBs installed we will not be able to get the clin-seq builds to succeed, clin-seq update-analysis will not work, copy number analysis in somatic-variation will not work, and possibly others.

**Comment by malachig** [comment]
In the module mentioned above:
/opt/gms/GD0T679/sw/genome/lib/perl/Genome/Model/Tools/CopyNumber/PlotSegmentsFromBamsWorkflow.pm

A call is made to: Genome::Sys->dbpath().
`my $file = Genome::Sys->dbpath("tgi-misc-annotation","human-build$refseq_version-20130113") . "/$file_type.csv";`

This method in turn calls:

`$dbpath = $class->_find_in_genome_db_paths($name, $version);`

This in turn expects a path with a particular structure to exist.  This does not exist because it has not been created in the sGMS.  The reason is that there is a confusing duplication of the file based databases within TGI.  For example, we have these two:
/gsc/scripts/opt/genome/db/tgi/misc-annotation/human/build37-20130113/
/gsc/scripts/opt/genome/db/tgi-misc-annotation/human-build37-20130113/

Those appear to contain identical files...

When you install the misc-annotation database in the sGMS, the first style is used.  The code in Genome::Sys expects the second style to be used.

Apart from this issue, we really should not be hard coding the path above in the first place.  The 'tgi-misc-annotation' annotation object should be an input of the somatic-variation model and the path to the database should be obtained by querying object.  With the hard-coding as it is now, you must install this version of the misc-annotation database in addition to any others you might need and the results will only be valid for human runs...

**Comment by malachig** [comment]
For now I have just fixed the hard coding to use the expected style as follows:

``` perl
    for my $file_type ("gaps", "centromere") {
        my $accessor = $file_type . "_file";
        unless ($self->$accessor) {
            $self->status_message("attempting to resolve dbpath for build_version '$refseq_version' and file_type '$file_type'");
            my $file = Genome::Sys->dbpath("tgi/misc-annotation/human","build$refseq_version-20130113") . "/$file_type.csv";
            unless (-e $file) {
                die $self->error_message("Could not find the $file_type file located at $file");
            }
            $self->$accessor($file);
        }
    }
```

This change was committed to gms-core master branch, tested and pushed.  Then I committed it to gms-core gms-pub branch for use in the sGMS. 

https://github.com/genome/gms-core/commit/ec9c5f70bd577a6ad8409a977c4fa48839a30f15
https://github.com/genome/gms-core/commit/ac5a8f86dd3b0c63761f8282966c73b745f1679d

**Comment by malachig** [comment]
The plot-segment step in somatic-variation is now succeeding.  Closing this issue for now.
