### ISSUE TITLE
Where are resource requests (cpus, mem, tmp space) defined for major compute steps?

### ISSUE THREAD

**Issue by malachig** [genome/gms#54]
TopHat alignments in the rna-seq pipelin: 
Genome/InstrumentData/Command/AlignReads/PerLaneTophat.pm

BWA alignments in the reference-alignment pipeline: 
Genome/InstrumentData/AlignmentResult/Bwa.pm

Others to consider?

**Comment by obigriffith** [comment]
In order to run even the toy datasets (1/100th downsampled bams) on a consumer box (e.g., 8 cpus and 64gb of ram) we will need to reduce the default resources requests otherwise we get into a hung state where jobs appear to be running but are actually waiting on resources that will never appear.

Some steps that should have resources reduced:
RNAseq pipeline:
Picard G+C Bias: 16GB -> 4 or 8GB
Collect Picard Metrics: 16GB -> 4 or 8GB
per_lane_tophat_2: 12cpus -> 4 or 8 cpus
RNAseq Cufflinks Expression: 64GB -> 8GB?

**Comment by obigriffith** [comment]
From Jason, for fixing the number of cpus for per_lane_tophat:

Genome::InstrumentData::Command::AlignReads::PerLaneTophat is the correct place.
See the comment in Genome::InstrumentData::AlignmentResult::PerLaneTophat before required_rusage();

**Comment by obigriffith** [comment]
A potential (hack) fix for this solution is to globally reduce memory and cpu requests for openlava systems to some max. I created a new environment variable in https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/genome.conf. If operating on a standalone system and using small test dataset you can set this variable.

``` shell
export WF_LOW_RESOURCES=1
```

This will cause https://github.com/genome/tgi-workflow/blob/gms-pub/lib/Workflow/Dispatcher/Lsf.pm to max out at 4cpus and 4GB of ram for any job request.

``` perl
    if ($OPENLAVA && $ENV{'WF_LOW_RESOURCES'}==1){
      if($job->resource->min_proc>4){
        $job->resource->min_proc(4);
      }
      if($job->resource->mem_request>4000){
        $job->resource->mem_request(4000);
      }
    }
```

**Comment by sakoht** [comment]
That is a great idea!  If necessary there could be a limit in each variable right in the config.

**Comment by obigriffith** [comment]
For somatic variation I am still running into the hung state where insufficient resources exist to continue. Specifically only 8 jobs can start and sometime this is not enough to get past a bottleneck. Pending jobs report 'max slot limit reached'. This can be fixed as follows:

Edit /opt/openlava-2.2/etc/lsb.hosts to change MXJ value for 'default' host (e.g., to 16) instead of '!' which by default makes the number of jobslots equal to the number of CPUs on all hosts (in this case 8). It should look something like as follows:

```
Begin Host
HOST_NAME     MXJ JL/U   r1m    pg    ls     tmp  DISPATCH_WINDOW  # Keywords
default       16   ()     ()    ()    ()     ()     ()       # Example
End Host
```

To restart the openlava service:

``` shell
sudo /etc/init.d/openlava restart
```

Finally to check that your change worked:

> bhosts
> HOST_NAME          STATUS       JL/U    MAX  NJOBS    RUN  SSUSP  USUSP    RSV 
> GGMS               ok              -     16     13     13      0      0      0

**Comment by obigriffith** [comment]
It seems that 16 cpus is not enough to make it through wgs somatic-variation with getting hung. Perhaps try 24. More total memory will be needed in the box so that each of these 24 potential jobs has at least some minimal amount of memory available to it.

**Comment by malachig** [comment]
We need to document known steps the user can take to improve performance (run times) on single box including environment variables that can be set, openlava configuration tweaks, and relevant code that could be modified.  This should be placed on the GMS wiki, then reference from here and this issue closed.

**Comment by malachig** [comment]
I have started a wiki page to document how the user can adjust resource requests for particular compute intensive steps here:

https://github.com/genome/gms/wiki/Where-resource-requests-are-defined

Closing this issue now.
