### ISSUE TITLE
Create a small test data set for benchmarking purposes

### ISSUE THREAD

**Issue by malachig** [genome/gms#64]
Create a sub-sampled version of all 10 BAM files for HCC1395 (aka TST1).  These are whole genome (tumor/normal), exome (tumor/normal), and rna-seq (tumor/normal) data.

Create sub-sampled versions of each BAM that meet the follow criteria:
- Contents of BAM file, including complete header are _identical_ to the
  original file, except for the number of reads
- Name each BAM file is identical to original but simply lives in a new
  location (place them anywhere for now and we will decide their final
  location later.
- Each BAM file has 1% of the reads of the original BAM file.  You
  should be able to generate these using something like: 'samtools view -s
  0.01'. Or do the equivalent with Picard.  
- Make sure read-pairing is maintained when creating the sub-sampled versions.

The full sized BAMs can be listed as follows within TGI:

``` bash
genome instrument-data list solexa --filter individual.common_name=TST1
--style tsv --show id,library_name,bam_path | grep -v -i pooled | cut -f 1,3
```

id    bam_path
2891322951 /gscmnt/gc6001/production/csf_135293260/gerald_D1VCPACXX_1.bam
2891323123 /gscmnt/gc6001/production/csf_135291690/gerald_D1VCPACXX_6.bam
2891323124 /gscmnt/gc6001/production/csf_135292156/gerald_D1VCPACXX_7.bam
2891323125 /gscmnt/gc6001/production/csf_135291998/gerald_D1VCPACXX_8.bam
2891323147 /gscmnt/gc6001/production/csf_135294298/gerald_D1VCPACXX_5.bam
2891323150 /gscmnt/gc6001/production/csf_135291736/gerald_D1VCPACXX_4.bam
2891323174 /gscmnt/gc6001/production/csf_135290829/gerald_D1VCPACXX_2.bam
2891323175 /gscmnt/gc6001/production/csf_135290878/gerald_D1VCPACXX_3.bam
2891351066
/gscmnt/gc6001/production/csf_135417932/gerald_C1TD1ACXX_7_ATCACG.bam
2891351068
/gscmnt/gc6001/production/csf_135416282/gerald_C1TD1ACXX_7_CGATGT.bam

The sub-sampled versions can be placed here (within TGI):
/gscmnt/sata132/techd/mgriffit/standalone_gms/hcc1395_1percent/

**Comment by malachig** [comment]
From Zach:

The files you requested are in the specified directory as well as the bash script used, and a .log file:

/gscmnt/sata132/techd/mgriffit/standalone_gms/hcc1395_1percent/

I have confirmed that the headers are identical with samtools view -H

I used picard instead of samtools as based on the discussion we had if a read is sub-sampled it's pair would need to be sub-sampled as well. I know picard does this and while I suspect samtools does as well I could not confirm my assumption in samtools documentation. Let me know if you would rather me use samtools and I will re-run the files.

**Comment by malachig** [comment]
I have copied the sub-sampled data to the staging dir:
/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/subsampled_bams/hcc1395_1percent/

http://genome.wustl.edu/pub/software/gms/testdata/GMS1/subsampled_bams/hcc1395_1percent/

Within a test install (e.g. a GMS virtual machine), try swapping the full size bams with these small ones and running the pipelines to speed up development/debugging.

**Comment by malachig** [comment]
I added a simple script to replace the large TST1 BAM files with the sub-sampled version described above.  

https://github.com/genome/gms/commit/73bca84b5c95dc74cdc36ffc0ea4610d30df99c1

https://github.com/genome/gms/blob/ubuntu-12.04/setup/use_sampled_tst1_data.pl

**Comment by obigriffith** [comment]
The above steps have accidentally skipped downsampling the RNAseq data. This is because unusually the RNAseq library names, for the data we want, include the phrase "pooled" and have been lost with the above grep command after listing. Instead we want something like:

``` bash
genome instrument-data list solexa --filter individual.common_name=TST1 --style tsv --show id,library_name,bam_path | grep -v -i -E "2891350970|2891351041"
```

id  bam_path
2891322951  /gscmnt/gc6001/production/csf_135293260/gerald_D1VCPACXX_1.bam
2891323123  /gscmnt/gc6001/production/csf_135291690/gerald_D1VCPACXX_6.bam
2891323124  /gscmnt/gc6001/production/csf_135292156/gerald_D1VCPACXX_7.bam
2891323125  /gscmnt/gc6001/production/csf_135291998/gerald_D1VCPACXX_8.bam
2891323147  /gscmnt/gc6001/production/csf_135294298/gerald_D1VCPACXX_5.bam
2891323150  /gscmnt/gc6001/production/csf_135291736/gerald_D1VCPACXX_4.bam
2891323174  /gscmnt/gc6001/production/csf_135290829/gerald_D1VCPACXX_2.bam
2891323175  /gscmnt/gc6001/production/csf_135290878/gerald_D1VCPACXX_3.bam
2891351066  /gscmnt/gc6001/production/csf_135417932/gerald_C1TD1ACXX_7_ATCACG.bam
2891351068  /gscmnt/gc6001/production/csf_135416282/gerald_C1TD1ACXX_7_CGATGT.bam
2891354555  /gscmnt/gc6001/production/csf_135450623/gerald_C1TD1ACXX_8_ACAGTG.bam
2893585922  /gscmnt/gc6001/production/csf_142880229/gerald_C2DBEACXX_3.bam

For reference these correspond to data types as follows:
WGS Tumor   gerald_D1VCPACXX_1.bam
WGS Tumor   gerald_D1VCPACXX_2.bam
WGS Tumor   gerald_D1VCPACXX_3.bam
WGS Tumor   gerald_D1VCPACXX_4.bam
WGS Tumor   gerald_D1VCPACXX_5.bam
WGS Normal  gerald_D1VCPACXX_6.bam
WGS Normal  gerald_D1VCPACXX_7.bam
WGS Normal  gerald_D1VCPACXX_8.bam
Exome   Tumor   gerald_C1TD1ACXX_7_ATCACG.bam
Exome   Normal  gerald_C1TD1ACXX_7_CGATGT.bam
RNAseq  Tumor   gerald_C1TD1ACXX_8_ACAGTG.bam
RNAseq  Normal  gerald_C2DBEACXX_3.bam

**Comment by obigriffith** [comment]
I have added downsampled versions of the two missing RNAseq instrument data to:
/gscmnt/sata132/techd/mgriffit/standalone_gms/hcc1395_1percent

downsample.ssh contains the additional commands needed. NOTE: because of the different nature of tophat bams I had to use 'VALIDATION_STRINGENCY=LENIENT' which allows Picard validation errors to be turned into warnings. 

The new files and updated .sh file were copied to the staging dir:
/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/subsampled_bams/hcc1395_1percent/

**Comment by obigriffith** [comment]
An additional set of further downsampled (0.1 percent) data was created for even faster iteration.These were produced in the same manner as above and copied to the staging dir here:
/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/subsampled_bams/hcc1395_1tenth_percent/

**Comment by malachig** [comment]
Everything seems to be working smoothly with these small test data sets.  In some cases they do not reduce run times of pipelines as much as one would hope (rna-seq and differential-expression especially) but we still see a substantial drop and no crashes related to manually hacking the BAM files for existing instrument data down to 1/100th or 1/1000th the size.

One caveat with testing.  If you want to rsync the GSM1 payload, you need to move the original BAMs back into place to prevent rsync from downloading them again...

**Comment by malachig** [comment]
Many undocumented iterations to these test data sets have been made.  All the latest versions are here:http://genome.wustl.edu/pub/software/gms/testdata/GMS1/subsampled_bams/

The latest/greatest test data set is this one: 'hcc1395_1tenth_percent_chr_21_22_targeted_v2/   '

This data set is an attempt to optimize for speed of processing but also produce real mutation/expression events across all of the types.

Use the following script to install it in a test sGMS system:
gms/setup/use_sampled_tst1_data.pl

**Comment by malachig** [comment]
Use of the down-sampled data is now handled by: `gms/setup/prime-system.pl`.

An alternate method for use of arbitrary data sets including the down-sampled data is also being described here:
https://github.com/genome/gms/wiki/Beginner%27s-Guide-to-Data-Import

The actual test data set seems to be working smoothly.  Closing this issue.
