### ISSUE TITLE
ERROR: Calling get on SoftwareResult (unless getting by id) is slow and possibly incorrect

### ISSUE THREAD

**Issue by malachig** [genome/gms#73]
I have noticed these non fatal errors in various places when pipelines are running:

ERROR: Calling get on SoftwareResult (unless getting by id) is slow and possibly incorrect.

Is there a generic fix when we encounter these?

This particular example is from:
Genome/Model/Event/Build/ReferenceAlignment/CoverageStats.pm

``` perl
    79     unless ($roi_reference->is_compatible_with($reference)) {
    80         if(Genome::Model::Build::ReferenceSequence::Converter->get(source_reference_build => $roi_reference, destination_reference_build => $reference)) {
    81             $self->status_message('Will run converter on ROI list.');
    82         } else {
    83             $self->error_message('reference sequence: ' . $reference->name . ' does not match the reference on the region of interest: ' . $roi_reference->name);
    84             return;
    85         }
    86     }

```

I have a vague recollection that using get_or_create() instead of get() may be more correct?

**Comment by ghost** [comment]
On Jan 17, 2014, at 11:50 AM, Malachi Griffith wrote:

> I have noticed these non fatal errors in various places when pipelines are running:
> 
> ERROR: Calling get on SoftwareResult (unless getting by id) is slow and possibly incorrect.
> 
> Is there a generic fix when we encounter these?
> 
> This particular example is from:
> Genome/Model/Event/Build/ReferenceAlignment/CoverageStats.pm
> 
> ```
> 79     unless ($roi_reference->is_compatible_with($reference)) {
> 80         if(Genome::Model::Build::ReferenceSequence::Converter->get(source_reference_build => $roi_reference, destination_reference_build => $reference)) {
> 81             $self->status_message('Will run converter on ROI list.');
> 82         } else {
> 83             $self->error_message('reference sequence: ' . $reference->name . ' does not match the reference on the region of interest: ' . $roi_reference->name);
> 84             return;
> 85         }
> 86     }
> ```
> 
> I have a vague recollection that using get_or_create() instead of get() may be more correct?
> 
> —
> Reply to this email directly or view it on GitHub.

If you call ->get() in scalar context and you're not querying by the id property (and only the id property), then you will see this warning.  One way to fix this problem is change the context to not be scalar.  One possible solution:

> ```
> 79         my @sr = Genome::Model::Build::ReferenceSequence::Converter->get(source_reference_build => $roi_reference, destination_reference_build => $reference);
> 
> 80         if(@sr) {
> ```

Michael

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by malachig** [comment]
Thanks @mkiwala-g.  I have applied this fix to gms-core master and gms-pub branches here:

https://github.com/genome/gms-core/commit/56965a2d68b8344412334332457f28a4c62fd5d7
https://github.com/genome/gms-core/commit/e90e0213ca14e71bd4bb8e830f95fc65c9e2b2d8

**Comment by malachig** [comment]
This issue has been resolved.
