### ISSUE TITLE
Can't locate object method "error_message"

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#77]
Multiple steps in clin-seq are reporting similar errors along the lines of:

2014-01-20 21:28:50-0600 GGM: Command module died or returned undef.
2014-01-20 21:28:50-0600 GGM: Can't locate object method "error_message" via package "Genome::Model::ClinSeq::Util" at /opt/gms/AUIS907/sw/workflow/lib/Workflow/OperationType/Command.pm line 362
2014-01-20 21:28:50-0600 GGM:   Genome::Model::ClinSeq::Util::loadEntrezEnsemblData('-cancer_db', 'Genome::Db::Tgi::CancerAnnotation=HASH(0x5b118a0)') called at /opt/gms/AUIS907/sw/genome/lib/perl/Genome/Model/ClinSeq/Command/TophatJunctionsAbsolute.pm line 105
2014-01-20 21:28:50-0600 GGM:   Genome::Model::ClinSeq::Command::TophatJunctionsAbsolute::execute('Genome::Model::ClinSeq::Command::TophatJunctionsAbsolute=HASH...') called at /opt/gms/AUIS907/sw/ur/lib/Command/V2.pm line 214
2014-01-20 21:28:50-0600 GGM:   Command::V2::execute('Genome::Model::ClinSeq::Command::TophatJunctionsAbsolute=HASH...') called at /opt/gms/AUIS907/sw/workflow/lib/Workflow/OperationType/Command.pm line 362

**Comment by ghost** [comment]
"error_message" is not a method on Genome::Model::ClinSeq::Util, yet in Util.pm, I see code such as :

``` perl
my $class = __PACKAGE__;
...
die $class->error_message(...);
```

The **PACKAGE** token expands to Genome::Model::ClinSeq::Util, so that example code tries to call error_message() on a package which does not have an error_message() method.

**What makes calling error_message() work in other packages?**
Other packages have code such as this:

``` perl
class Genome::Model::Somatic {
    is  => 'Genome::Model',
...
};
```

Which causes the package to inherit from Genome::Model, which has the error_message() method, so that the subclass can also call error_method().

I'm not convinced that Util.pm is meant to be a sub-class of Genome::Model, so I don't think this is the correct solution here.  Util.pm appears to be implementing what I think of as a "role", instead of using inheritance.  So I don't think inheritance is the answer here.

**How can we make the warnings go away?**
Two solutions that come immediately to mind are to either supply an error_message() method on the Util package or adjust code so that $class contains a name of the calling class instead of Util.pm's package name.  I'd rather lean on the existing error_message() method instead of rolling our own, so I prefer making $class contain the name of the calling class.

Here is a _completely untested_ idea:

Change Util.pm to be more like this:

``` perl
sub loadEntrezEnsemblData {
  my $class = shift;
  my %args = @_;
...
  die $class->error_message(...);
}
```

And change calling code (such as  TophatJunctionsAbsolute.pm):

``` perl
  #Get Entrez and Ensembl data for gene name mappings
  my $entrez_ensembl_data = $self->loadEntrezEnsemblData(-cancer_db => $cancer_annotation_db);
```

By changing the calling semantics, $self is passed as the first argument to loadEntrezEnsemblData() (stored in $class; maybe we should change that name), so that when $class->error_message() is called, it is called on the TophatJunctionsAbsolute package which has an error_message() method.

**Comment by ghost** [comment]
I see now that $self used to be defined in the Util.pm methods and was later changed to $class.

Another idea (not originally my idea) that I think could work well, does not depend on $class or $self being defined in Util.pm.  Instead, it uses exceptions to pass the error message back to the caller, and let's the caller be responsible for handling the error message in whatever way it sees fit (eg, by calling $self->error_message()):

``` perl
package Genome::Model::ClinSeq::Util;

sub loadEntrezEnsemblData {
  my %args = @_;
...
  die $some_error_message;

package Genome::Model::ClinSeq::Command::TophatJunctionsAbsolute;
use Try::Tiny;

sub execute {
  my $self = shift;
...
  try {
    &loadEntrezEnsemblData(...)
  }
  catch {
    die $self->error_message($_);
  }; 
...
}
```

**Comment by malachig** [comment]
There are at least three modules where we need to clean things up.  It looks like @gatoravi  was experimenting while working on this issue https://jira.gsc.wustl.edu/browse/TD-486

Each currently uses a different method for accessing the error_message and status_message methods: 
Genome/Model/ClinSeq/Converge.pm

```
use Genome;
use Data::Dumper;
use Genome::Model::ClinSeq::Util qw(:all);
die Genome::Model->error_message("\n\tDid not find the correct number of successful models/builds");
```

Genome/Model/ClinSeq/RnaSeqUtil.pm

```
use Genome;
use Genome::Model::ClinSeq::Util qw(:all);
die Command->error_message("\n\nRequired column not found: 'FPKM_status' or 'status'");
```

Genome/Model/ClinSeq/Util.pm

```
#No use of Genome or Util ...
my $class = __PACKAGE__;
die $class->error_message("\nSpecified working directory: $base_path does not appear valid! Create a working directory before proceeding\n\n");
```

**Comment by sakoht** [comment]
Those things will need to inherit from UR::ModuleBase or UR::Object for
error_message to work.

Check $class->isa("UR::ModuleBase"), $class->isa("UR::Object") ...and if
they are false, check @TheClass::ISA for what it actually inherits from to
see why.

On Tue, Jan 21, 2014 at 12:47 PM, Malachi Griffith <notifications@github.com

**Comment by malachig** [comment]
As a starting point we have made the clin-seq modules in question pass $self around as suggested by @mkiwala-g above.  This seems to have got us past this issue and into the next crash...  Relevant commits here:

master:
https://github.com/genome/gms-core/commit/a4347f35c120a88a96a9a4bfc3babb3c066ba261
https://github.com/genome/gms-core/commit/14cd9262b11812ed678aec1122d0b81a4193fde2
https://github.com/genome/gms-core/commit/4f48c68a8c0821ecab3ef058bf5f740a4c56c080
https://github.com/genome/gms-core/commit/102627d482b73c62841b76a9ea9a3f14926e50b3
https://github.com/genome/gms-core/commit/7b1e24d0f645de28b145badad9a07fb1445cdebe

gms-pub:
https://github.com/genome/gms-core/commit/ed429f11d06be9f9ae70c77413e6faf98cc3c4ea

**Comment by obigriffith** [comment]
This seems to have been resolved. My clinseq builds on GGMS get past this.
